### ISSUE TITLE
NSG GeoPackage Tiling Profile 2.0 Support?

### ISSUE THREAD

**Issue by geospatialmapmashup** [ngageoint/mage-ios-sdk#8]
Does MAGE iOS SDK been updated to support the NGA's NSG GeoPackage Tiling Profile Specification?  (NSG) GeoPackage Encoding Standard 2.0
Interoperability Standard
(2016-09-14)

**Comment by danielbarela** [comment]
Please see ngageoint/GeoPackage#4
